Projectapp/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
    url(r'^', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url(r'^register/$', views.register, name='register'),
   url(r'^login_user/$', views.login_user, name='login_user'),
   url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
   url(r'^logout_user/$', views.logout_user, name='logout_user'),
   url(r'^recommend/$', views.recommend, name='recommend'),
  
]

movies/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from decimal import Decimal


class Picture(models.Model):
    user = models.ForeignKey(User, default=1)
    picture_id = models.IntegerField(default=0)
    picture_title = models.CharField(max_length=500)
    genres = models.CharField(max_length=1000)
    ratings = models.DecimalField(max_digits=10, decimal_places=1)
    picture_logo = models.CharField(max_length=1000, default='/media/noimage.jpg')

    def __str__(self):
        return self.picture_title


class Film(models.Model):
    film_id = models.IntegerField(default=0)
    film_title = models.CharField(max_length=500)
    pop_genres = models.CharField(max_length=1000)
    pop_ratings = models.DecimalField(max_digits=10, decimal_places=1)
    pop_picture_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.film_title

movies/forms.py
from django import forms 
from django.contrib.auth.models import User

from .models import Picture, Film

class PictureForm(forms.ModelForm):

    class Meta:
        model = Picture
        fields = ['picture_id', 'picture_title', 'genres', 'ratings', 'picture_logo']

class FilmForm(forms.ModelForm):

    class Meta:
        model = Film
        fields = ['film_id', 'film_title', 'pop_genres', 'pop_ratings', 'pop_picture_logo']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

movies/views.py
from django.views import generic
from .models import Picture, Film
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm, PictureForm
from django.shortcuts import render
import numpy as np
import pandas as pd
from popularity_based import Popularity_based
from collaborative_filtering import Collaborative_filtering
from django.core.urlresolvers import resolve
import unicodedata


from updater import *

import imdb
from BeautifulSoup import BeautifulSoup
import urllib2 
import os
import requests
import bs4
import json,requests,unicodedata,urllib2
import time


# set some print options
np.set_printoptions(precision=4)
np.set_printoptions(threshold=5)
np.set_printoptions(suppress=True)
pd.set_option('precision', 3, 'notebook_repr_html', True, )
# init random gen
np.random.seed(2)


users_file = "/media/sourabhkondapaka/Sourabh's/main_project/sandbox/ml-latest-small/ratings.csv"
movies_file = "/media/sourabhkondapaka/Sourabh's/main_project/sandbox/ml-latest-small/movies.csv"
users = pd.read_table(users_file,sep=',', header=None,names = ['user_id','movie_id','rating','timestamp'])
movies = pd.read_table(movies_file, sep=',')
# Remove the line below if it throws any error when using popularity based or collaborative_filtering
movies.columns = ['movie_id','title','genres']
ratings_file = "/home/sourabhkondapaka/Desktop/ratingsss.csv"

#Collaborative_filtering code
cf = Collaborative_filtering(ratings_file,movies)
cf.compute_svd()


#Popularity_based code
pb = Popularity_based(users, movies)
pb.create()
top_movies = pb.recommend()

top_movies_names  = []
top_movies_ids  = []

for movie in top_movies:
    top_movies_names.append(movie[1])
    top_movies_ids.append(movie[0])



#Details of movie code
ia = imdb.IMDb()
url = "http://www.omdbapi.com/?t="


#keys in json string are :
'''
[u'Plot', u'Rated', u'Title', u'Ratings',
 u'DVD', u'Writer', u'Production', u'Actors',
  u'Type', u'imdbVotes', u'Website', u'Poster', u'Director',
   u'Released', u'Awards', u'Genre', u'imdbRating',
    u'Language', u'Country', u'BoxOffice', u'Runtime',
     u'imdbID', u'Metascore', u'Response', u'Year']
'''

def recommendz(request):
    return


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'movies/login.html')
    else:

        #moviez = Film.objects.all()
        #all_pictures = Picture.objects.all()    'all_pictures': all_pictures,
        #return render(request, 'movies/index.html', { 'moviez': moviez})        
        #pb = Popularity_based(users, movies)
        #pb.create()
        #top_movies = pb.recommend()


        return render(request, 'movies/index.html', {'data': zip(top_movies_names, top_movies_ids)})


def detail(request, movie_id):
    #v = request.POST.get('rate')  
    #value = v.encode("utf-8")
    if(request.GET.get('mybtn')):
        val =  float(request.GET.get('rate'))
        print "value in val is \n\n\n\n",val
        rate_movie(int(request.user.id) + 671,movie_id,val) 

    if not request.user.is_authenticated():
        return render(request, 'movies/login.html')
    else:
        user = request.user
        #picture = get_object_or_404(Picture, pk=picture_id)
        #getting details from omdbapi
        bb = str(movies.ix[movies['movie_id'] == int(movie_id) ]['title']).split()    
        q = bb.index('Name:')
        bb = ' '.join(bb[1:q])
        item = ia.search_movie(bb)[0]
        name = str(item)        
        ll = name.split()
        #ll = '+'.join(ll)
        movie_url = url + '+'.join(ll)
        movie_url += "&plot=full"
        content = urllib2.urlopen(movie_url).read()
        jsontopython = json.loads(content)

        #Values passed to details.html file
        plot = jsontopython['Plot']
        writers = jsontopython['Writer']
        producers = jsontopython['Production']
        actors = jsontopython['Actors']
        director = jsontopython['Director']
        awards = jsontopython['Awards']
        runtime = jsontopython['Runtime']
        genre = jsontopython['Genre']
        #movies similar to this movie.
        similar_movies,similar_ids = cf.get_similar_movies(int(movie_id)) 
        #for mov in similar_movies:
        #   print mov
        return render(request, 'movies/detail.html', {'data':zip(similar_movies,similar_ids), 'plot':plot,'writers':writers,'producers':producers, 'actors':actors,'director':director,'awards':awards,'runtime':runtime,'genre':genre})
        #return render(request,'movies/detail.html',{'plot':plot})

def recommend(request):
    cur_usr = (request.user.id) + 671
    pc = ratings.movie_id[ratings.user_id == cur_usr]  # gets all the movies rated by this user
    ad = pc.tolist()    
    if  any(ratings['user_id'] == cur_usr):
        if not ad:
            reco_movies , reco_ids =  cf.recommend_movies(cur_usr)
            return render(request, 'movies/recommend.html',{'data': zip(reco_movies, reco_ids)})

    else:
        return render(request, 'movies/recommend2.html',{})







def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'movies/index.html', {'data': zip(top_movies_names, top_movies_ids)})

            else:
                return render(request, 'movies/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'movies/login.html',
                          {'error_message': 'Invalid login , Please Check your details correctly and try again'})
    return render(request, 'movies/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'movies/index.html', {'data': zip(top_movies_names, top_movies_ids)})

    context = {
        "form": form,
    }
    return render(request, 'movies/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'movies/login.html', context)

def request_page(request):
    users_id = request.user.id + 671
    if(request.POST.post('mybtn')):
        updater.rate_movie(672,6251,float(request.POST.post('rate')))

movies/templates/movies/base.html
<!DOCTYPE <html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Movies{% endblock %}</title>
    <!-- Loads the path to your static files --> 
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> 
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movies:index' %}">Home</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'movies:index' %}">
                        <span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp; Movies
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>


            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                   <a href="{% url 'movies:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; User Settings
                    </a>
                </li>
            
            </ul>




        </div>



        
    </div>
    
</nav>

{% block body %}
{% endblock %}


</body>
 </html>>
 

movies/templates/movies/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'movies/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movies:index' %}">Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'movies:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'movies:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movies/templates/movies/detail.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %}Movie Details{% endblock %}
{% block body %}
 <h4>Details for the movie</h4>
    <p>{{ plot }}</p>
    <center>
    <h6>Writers: {{ writers }}</h6>
    <h6>Producers: {{ producers }}</h6>
    <h6>Actors: {{ actors }}</h6>
    <h6>Director: {{ director }}</h6>
    <h6>Awards: {{ awards }}</h6>
    <h6>Runtime: {{ runtime }}</h6>
    <h6>Genre: {{ genre }}</h6>
    </center>
 <form action="#" method="GET" name="rate_movie">
     {% csrf_token %}
  Ratings: <input type="number" name="rate" step="0.1" min="1" max="5"><br>
  <input type="submit" value="Submit" name="mybtn">
</form>

               {% for movie,id in data %}
                 <div class="col-sm-4 col-lg-2">
                   <div class="style_prevu_kit">
                    <div class="thumbnail">
                       <a href="{% url 'movies:detail' id %}">
                          <img src="{% static "movies/images/images2/" %}{{ movie }}" alt="Hi!" class="img-responsive" height="300" width="350"/>
                       </a>
                        <div class="caption">
                            <h4>{{ movie }}</h4>
                        </div>
                        </div>
                        </div>
                </div>
            {% endfor %}


{% endblock %}

movies/templates/movies/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

movies/templates/movies/index.html
{% extends "movies/base.html" %}
{% load static %}

{% block body %}
<div class="albums-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
        <center>
            <h2>Welcome {{ user.username }} </h2>
            <h2> <a href="{% url 'movies:recommend' %}">Click here to get recommend Movies for you </a></h2>
            <h2>These  are the most Popular movies  </center>
            {% for movie,id in data %}
                 <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                       <a href="{% url 'movies:detail' id %}">
                          <img src="{% static "movies/images/images2/" %}{{ movie }}" alt="Hi!" class="img-responsive" />
                       </a>
                        <div class="caption">
                            <h5>{{ movie }}</h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

movies/templates/movies/login.html
{% extends 'movies/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'movies:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'movies:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

movies/templates/movies/recommend.html
{% extends "movies/base.html" %}
{% load static %}

{% block body %}
<div class="albums-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h2>Welcome {{ user.username }}'s </h2>
            <h3>Recommend  movies for you {{ user.username }}</h3>
            {% for movie,id in data %}
                 <div class="col-sm-4 col-lg-2">
                   <div class="style_prevu_kit">
                    <div class="thumbnail">
                       <a href="{% url 'movies:detail' id %}">
                          <img src="{% static "movies/images/images2/" %}{{ movie }}" alt="Hi!" class="img-responsive" />
                       </a>
                        <div class="caption">
                            <h4>{{ movie }}</h4>
                        </div>
                        </div>
                        </div>
                </div>
            {% endfor %}
        </div>

</div>
{% endblock %}

movies/templates/movies/recommend2.html
{% extends "movies/base.html" %}
{% load static %}

{% block body %}
     <center>
            <h2>Welcome {{ user.username }} </h2>
     </center>
    <h2>you have not rated any movies , hence cant recommend any movies to you, please check the top ratings site for trending movies which you might like</h2>
    <a href="{% url 'movies:index' %}">Click here to Top movies </a>

{% endblock %}

movies/templates/movies/register.html
{% extends 'movies/base_visitor.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="panel-footer">
                    Already have an account? <a href="{% url 'movies:login_user' %}">Click here</a> to log in.
            </div>



	</div>


        
    </div>

</div>
{% endblock %}